---
- name: "Deploy New Version of Mini App"
  hosts: my_computer
  become: true
  tasks:

    - name: "1. Pull the latest image from Docker Hub"
      docker_image:
        name: "larkracl/mini-app" # 본인이 올린 이미지로 바꿔보기
        tag: "latest"
        source: pull
        force_source: yes

    - name: "2. Remove old container"
      docker_container:
        name: "my-running-app"
        state: absent
        force_kill: yes
    
    - name: "2-1. Kill any process using port 8080 (Safety First)"
      shell: "docker rm -f $(docker ps -q --filter 'publish=8080') || true"

    - name: "3. Run new container"
      docker_container:
        name: "my-running-app"
        image: "larkracl/mini-app:latest" # 본인이 올린 이미지로 바꿔보기
        state: started
        ports:
          - "8080:8080"